# Generated by Django 2.2.5 on 2020-01-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentNumber', models.TextField(default='B00000000')),
                ('StudentName', models.TextField(default='哈哈哈')),
                ('College', models.TextField(default='管理學院')),
                ('Department', models.TextField(default='資訊管理系')),
                ('Grade', models.TextField(default='一')),
                ('Gender', models.TextField(default='生理男')),
                ('CourseNumber', models.TextField(default='IM2002')),
                ('Year', models.TextField(default='100')),
                ('CourseName', models.TextField(default='管理學')),
                ('Category', models.TextField(default='必修')),
                ('Credit', models.TextField(default='3')),
                ('Professor', models.TextField(default='謝冠雄')),
                ('ProfessorNumber', models.TextField(default='T00001')),
                ('TAName', models.TextField(default='你是誰')),
                ('TANumber', models.TextField(default='TA000')),
                ('RollCall', models.TextField(default='不點名')),
                ('Attendance', models.TextField(default='0')),
                ('SweetScore', models.TextField(default='0')),
                ('FreeScore', models.TextField(default='0')),
                ('AcquisitionScore', models.TextField(default='0')),
                ('CourseGrade', models.TextField(default='A')),
                ('Recommendation', models.TextField(default='0')),
            ],
            options={
                'db_table': 'response',
            },
        ),
    ]
