# Generated by Django 3.0.2 on 2020-01-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TANumber', models.TextField(default='TA000')),
                ('CourseNumber', models.TextField(default='IM2002')),
            ],
            options={
                'db_table': 'assist',
            },
        ),
    ]
