# Generated by Django 3.0.2 on 2020-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_assist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNumber', models.TextField(default='IM2002')),
                ('CourseName', models.TextField(default='管理學')),
                ('Category', models.TextField(default='必修')),
                ('Credit', models.TextField(default='3')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
