# Generated by Django 3.0.2 on 2020-01-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNumber', models.TextField(default='IM2002')),
                ('SweetScore', models.TextField(default='0')),
                ('FreeScore', models.TextField(default='0')),
                ('RollCall', models.TextField(default='不點名')),
            ],
            options={
                'db_table': 'courseproperties',
            },
        ),
    ]
