# Generated by Django 3.0.2 on 2020-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200114_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNumber', models.TextField(default='IM2002')),
                ('AcquisitionScore', models.TextField(default='0')),
                ('Recommendation', models.TextField(default='0')),
                ('StudentName', models.TextField(default='哈哈哈')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
