# Generated by Django 3.0.2 on 2020-01-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfessorNumber', models.TextField(default='T00001')),
                ('TAName', models.TextField(default='你是誰')),
            ],
            options={
                'db_table': 'professor',
            },
        ),
    ]
