# Generated by Django 3.0.2 on 2020-01-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNumber', models.TextField(default='IM2002')),
                ('CourseGrade', models.TextField(default='A')),
                ('StudentNumber', models.TextField(default='B00000000')),
            ],
            options={
                'db_table': 'score',
            },
        ),
    ]
