# Generated by Django 3.0.2 on 2020-01-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentNumber', models.TextField(default='B00000000')),
                ('StudentName', models.TextField(default='哈哈哈')),
                ('Gender', models.TextField(default='生理男')),
                ('Grade', models.TextField(default='一')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
