# Generated by Django 3.0.2 on 2020-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TANumber', models.TextField(default='TA000')),
                ('TAName', models.TextField(default='你是誰')),
            ],
            options={
                'db_table': 'TA',
            },
        ),
    ]
