# Generated by Django 3.0.2 on 2020-01-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_ta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentNumber', models.TextField(default='B00000000')),
                ('CourseNumber', models.TextField(default='IM2002')),
            ],
            options={
                'db_table': 'take',
            },
        ),
    ]
