# Generated by Django 3.0.2 on 2020-01-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_take'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfessorNumber', models.TextField(default='T00001')),
                ('CourseName', models.TextField(default='管理學')),
            ],
            options={
                'db_table': 'teach',
            },
        ),
    ]
